site_name: The Data Armory
site_description: Python | Data Analysis | Machine Learning.

repo_url: https://github.com/everndah/the-data-armory
repo_name: everndah/the-data-armory

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      
 

  # Pallet Color
  palette:
    primary: black

  # Site Font
  font:
    text: Roboto

  features:
    - navigation.footer
    - content.code.copy
    - content.code.py.annotate
    - search.suggest
    - search.highlight
    - toc.follow
    - navigation.instant
    - navigation.top
    - navigation.tabs

extra:
  # Social Links
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@thedataarmory
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheDataArmory
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ydC74P5saW

  markdown_extensions:  
    - pymdownx.highlight:
      anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
      generic: true
    - footnotes 
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - tables
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji 
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - md_in_html

plugins:
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
  - search

# Page tree
nav:
  - Home: index.md

  - Python Course:
      - Home: "python_index.md"
      - 00. What is Python: 00_what_is_python.ipynb
      - 01. Python Variables: 01_variables_in_python.ipynb
      - 02. Data Types: 02_python_data_types.ipynb
      - 03. Python Comments: 03_python_comments.ipynb
      - 04. Python Strings: 04_python_strings.ipynb

  - Statistics Course:
      - Home: "statistics_index.md"
      - 01. Structured and Unstructured Data: 01_Structured_and_Unstructured_Data.ipynb
      - 02. Data Frames : 02_data_frames.ipynb

  - Projects:
      - EDA/ML Projects: projects.md

#Footer Copyright Info
copyright: Copyright © 2023 The Data Armory.
